### ISSUE TITLE
Menue not showing up on Desktop

### ISSUE THREAD

**Issue by e1mo** [chaos-jetzt/website_pelican#11]
The menu is not being displayed on desktop by default. When you switch to mobile, display the menue and switch back to desktop view it stays visible.
This has possibly been introduced in #7.

**Comment by n0emis** [comment]
Are you on the latest version? Should have been fixed by a044845b8e36b49d9e0ab81d09dc53ea25f48048

**Comment by e1mo** [comment]
Well I guess another git pull wouldn't have hurt...
