### ISSUE TITLE
GitHub Pages for dev version?

### ISSUE THREAD

**Issue by rugk** [chaos-jetzt/website_pelican#18]
Könnten wir nicht GitHub Pages als dev Instanz nutzen…

Uhm… okay, hier mal eien PR als Test: https://github.com/chaos-jetzt/website_pelican/pull/17

**Comment by e1mo** [comment]
Wie in #17 beschrieben:

> I think this is obsoleted by #10 and #33. But even with 3 years of delay, thanks for the proposal!
