### ISSUE TITLE
CDNs entfernen

### ISSUE THREAD

**Issue by e1mo** [chaos-jetzt/website_pelican#6]
https://github.com/chaos-jetzt/website_pelican/blob/7f2c116a74e9f993bf0f3da8b9432e40a94af7b7/clean-blog/templates/base.html#L55-L65

_Originally posted by @YtvwlD in https://github.com/chaos-jetzt/website_pelican/pull/4_

**Comment by YtvwlD** [comment]
Brauchen wir überhaupt Support für IE8?

Font Awesome scheint nirgendwo benutzt zu werden.

Und die Schriften? Das einzige, was sich zu ändern scheint, ist die kursive Schrift oben auf dem Bild.
(links: ohne externe Schriften (Firefox), rechts: mit externen Schriften (Chromium))
![Screenshot](https://user-images.githubusercontent.com/5578100/78500928-a4dd9080-7759-11ea-8d59-659405a992b6.png)

**Comment by n0emis** [comment]
joa, stimmt. koennen eigentlich raus...
